---
- name: Update cache
  apt:
    update_cache: yes

- name: Debian/Ubuntu | Install apt-transport-https, ca-certificates and gpg
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gpg-agent
    state: present
    cache_valid_time: 3600
    install_recommends: false
    update_cache: true
  register: kibana_https_packages_installed
  until: kibana_https_packages_installed is succeeded

- name: Debian 9 (Stretch)
  when: (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] == "9")
  block:

    - name: Install OpenDistro dependencies
      apt:
        name: [
          'unzip', 'wget', 'curl', 'apt-transport-https', software-properties-common
        ]
        state: present

    - name: Add the repository key for Debian's Stretch Backports repository
      ansible.builtin.apt_key:
        keyserver: keyserver.ubuntu.com
        id: 648ACFD622F3D138

    - name: Add openjdk repository
      apt_repository:
        repo: "{{ package_repos.apt.openjdk.baseurl }}"
        state: present
        update_cache: yes
        filename: 'wazuh-openjdk'

- name: Install openjdk-11-jdk
  apt:
    name: openjdk-11-jdk
    state: present
  environment:
    JAVA_HOME: /usr

- name: Add Opendistro repository
  block:
    - name: Add apt repository signing key
      apt_key:
        url: "{{ package_repos.apt.opendistro.gpg }}"
        state: present

    - name: Add Opendistro repository
      apt_repository:
        repo: "{{ package_repos.apt.opendistro.baseurl }}"
        state: present
        filename: 'wazuh-opendistro'
        update_cache: yes

- name: Install OpenDistro
  apt:
    name: opendistroforelasticsearch={{ opendistro_version }}-1
    state: present
  register: install
  tags: install
