---
- name: restart wazuh-agent
  service:
    name: wazuh-agent
    state: restarted
    enabled: true

- name: restart windows-wazuh-agent
  win_service:
    name: WazuhSvc
    start_mode: auto
    state: restarted
